#!/bin/sh -e

PATH=/usr/sbin:/usr/bin:/sbin:/bin

if [ ! -x /usr/sbin/unbound ]; then
    exit 0
fi

if [ ! -x /lib/resolvconf/list-records ]; then
    exit 1
fi

CONF="/var/lib/unbound/forwarders.conf"
RESOLVCONF_FILES="$(/lib/resolvconf/list-records)"

if [ -z "RESOLVCONF_FILES" ]; then
    exit 0
fi

NS_IPS="$(sed -rne 's/^[[:space:]]*nameserver[[:space:]]+//p' $RESOLVCONF_FILES \
    | egrep -v '^(127\.|::1)' | sort -u)"

if [ -z "$NS_IPS" ]; then
    exit 0
fi

TMP_FILE="$(mktemp)"
cat > $TMP_FILE << EOF
forward-zone:
    name: "."
EOF

echo "$NS_IPS" | while read ip; do
    echo "    forward-addr: $ip" >> $TMP_FILE
done

mv "$TMP_FILE" "$CONF"

if [ -f "/etc/unbound/unbound_control.key" ]; then
    FWD="$(echo $NS_IPS | tr '\n' ' ')"
    unbound-control forward $FWD 1>/dev/null 2>&1
fi
